version: '3.8'

services:
  db-cleanup:
    build: .
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    restart: unless-stopped
    volumes:
      - ../logs:/app/logs
